"use client";
import { useState,type ReactNode } from "react";
import { readJson } from "@/lib/client-storage";
import type { AppSettings } from "@/lib/domain";
type Tab="today"|"saved"|"planner"|"grocery"|"insights";
const today=()=>new Date().toISOString().slice(0,10);
export default function NutritionWorkspace({tracker,settings}:{tracker:ReactNode;settings:AppSettings}){const [tab,setTab]=useState<Tab>("today");const tabs:[Tab,string][]=[["today","Today"],["saved","Saved meals"],["planner","Meal planner"],["grocery","Grocery list"],["insights","Insights"]];return <><div className="head"><h1>Nutrition</h1><p>Log faster, plan ahead, and understand your intake.</p></div><div className="row" style={{gap:8,flexWrap:"wrap",marginBottom:16}}>{tabs.map(([k,l])=><button key={k} className={`btn ${tab===k?"":"ghost"} sm`} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==="today"&&tracker}{tab==="saved"&&<SavedMeals/>}{tab==="planner"&&<MealPlanner settings={settings}/>} {tab==="grocery"&&<Grocery/>}{tab==="insights"&&<Insights settings={settings}/>}</>}
function SavedMeals(){const [items,setItems]=useState<any[]>(()=>readJson("pos_saved_meals",[]));const [name,setName]=useState("");const save=(n:any[])=>{setItems(n);localStorage.setItem("pos_saved_meals",JSON.stringify(n));};const log=(meal:any)=>{const key=`pos_nutri_${today()}`;const day=readJson<any>(key,{meals:[],water:0});day.meals.push(...meal.items);localStorage.setItem(key,JSON.stringify(day));};return <div className="card"><div className="between"><strong>Reusable meals</strong><div className="row"><input className="in" value={name} onChange={e=>setName(e.target.value)} placeholder="Meal name"/><button className="btn sm" onClick={()=>{if(name){save([...items,{name,items:[]}]);setName("");}}}>Add</button></div></div>{items.map((meal,i)=><div className="card" key={i} style={{marginTop:12,background:"rgba(255,255,255,.03)"}}><div className="between"><input className="in" value={meal.name} onChange={e=>save(items.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><div><button className="btn sm" onClick={()=>log(meal)}>Log today</button><button className="btn ghost sm" onClick={()=>save(items.filter((_,j)=>j!==i))}>Remove</button></div></div><textarea className="in" value={(meal.items||[]).map((x:any)=>`${x.name}|${x.cal}|${x.protein}|${x.carbs}|${x.fat}`).join("\n")} onChange={e=>save(items.map((x,j)=>j===i?{...x,items:e.target.value.split("\n").filter(Boolean).map(line=>{const [name,cal,protein,carbs,fat]=line.split("|");return{name,cal:+cal||0,protein:+protein||0,carbs:+carbs||0,fat:+fat||0,fiber:0};})}:x))} placeholder="Food|calories|protein|carbs|fat" style={{width:"100%",minHeight:100,marginTop:8}}/></div>)}</div>}
function MealPlanner({settings}:{settings:AppSettings}){const [plan,setPlan]=useState<any>(()=>readJson("pos_weekly_meals",{}));const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];const save=(d:string,k:string,v:string)=>{const n={...plan,[d]:{...(plan[d]||{}),[k]:v}};setPlan(n);localStorage.setItem("pos_weekly_meals",JSON.stringify(n));};return <><div className="card"><strong>Weekly plan · target {settings.calorieGoal} kcal / {settings.proteinGoal}g protein</strong></div><div className="grid g2" style={{marginTop:12}}>{days.map(d=><div className="card" key={d}><strong>{d}</strong>{["breakfast","lunch","dinner","snack"].map(k=><input key={k} className="in" value={plan[d]?.[k]||""} onChange={e=>save(d,k,e.target.value)} placeholder={k} style={{width:"100%",marginTop:8}}/>)}</div>)}</div></>}
function Grocery(){const plan=readJson<any>("pos_weekly_meals",{});const generated=Object.values(plan).flatMap((d:any)=>Object.values(d||{})).filter(Boolean);const [text,setText]=useState(()=>readJson("pos_grocery_list",generated.join("\n")));return <div className="card"><strong>Grocery list</strong><div className="muted" style={{fontSize:12}}>Generated from the weekly plan; edit into ingredients and quantities.</div><textarea className="in" value={text} onChange={e=>{setText(e.target.value);localStorage.setItem("pos_grocery_list",JSON.stringify(e.target.value));}} style={{width:"100%",minHeight:380,marginTop:12}}/></div>}
function Insights({settings}:{settings:AppSettings}){const rows=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);const day=readJson<any>(`pos_nutri_${d.toISOString().slice(0,10)}`,{meals:[],water:0});return{cal:(day.meals||[]).reduce((a:number,x:any)=>a+(+x.cal||0),0),protein:(day.meals||[]).reduce((a:number,x:any)=>a+(+x.protein||0),0),fiber:(day.meals||[]).reduce((a:number,x:any)=>a+(+x.fiber||0),0),water:+day.water||0};});const avg=(k:keyof typeof rows[0])=>Math.round(rows.reduce((a,x)=>a+(+x[k]||0),0)/7*10)/10;return <><div className="grid g4"><div className="card"><div className="lbl">AVG CALORIES</div><div className="val">{avg("cal")}</div></div><div className="card"><div className="lbl">AVG PROTEIN</div><div className="val">{avg("protein")}g</div></div><div className="card"><div className="lbl">AVG FIBER</div><div className="val">{avg("fiber")}g</div></div><div className="card"><div className="lbl">AVG WATER</div><div className="val">{avg("water")}L</div></div></div><div className="card" style={{marginTop:16}}><strong>Guidance</strong><p>{avg("protein")<settings.proteinGoal*.85?"Protein is below target. Pre-plan one reliable protein source for each main meal.":"Protein consistency is strong."}</p><p>{avg("fiber")<settings.fiberGoal*.8?"Add legumes, vegetables, fruit, or whole grains to close the fiber gap.":"Fiber intake is close to target."}</p><div className="muted">Nutrition values and AI estimates are approximate and not medical advice.</div></div></>}
