"use client";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import type { AppSettings } from "@/lib/domain";
import { addDays, buildReviews, collectSubjects, localDate, readStore, studySessions, subjectsFor, writeStore, type ReviewItem, type StudySession, type StudySubject } from "@/lib/study";

type Tab="today"|"courses"|"plan"|"calendar"|"review"|"quiz"|"library"|"progress";
const tabs:[Tab,string,string][]=[["today","Today","▶"],["courses","Courses","🎓"],["plan","Study Plan","📋"],["calendar","Calendar","📅"],["review","Review","🧠"],["quiz","Quiz & AI","✨"],["library","Library","🔎"],["progress","Progress","📈"]];
const mins=(time?:string)=>{const match=String(time||"").match(/\d+/);return match?+match[0]:25;};

export default function StudyDashboard({settings,tick,onRefresh,planner,coursePlanner,curriculum}:{settings:AppSettings;tick:number;onRefresh:()=>void;planner:ReactNode;coursePlanner:ReactNode;curriculum:ReactNode}){
  const [tab,setTab]=useState<Tab>("today");const [date,setDate]=useState(localDate());void tick;
  return <><div className="head"><h1>Study</h1><p>Plan, focus, revise, and measure your learning in one workspace.</p></div><div className="row" style={{gap:8,flexWrap:"wrap",marginBottom:16}}>{tabs.map(([key,label,icon])=><button key={key} className={`btn ${tab===key?"":"ghost"} sm`} onClick={()=>setTab(key)}>{icon} {label}</button>)}</div>
    {tab==="today"&&<TodayStudy date={date} setDate={setDate} onRefresh={onRefresh}/>} {tab==="courses"&&<><CourseOverview/>{coursePlanner}{curriculum}</>} {tab==="plan"&&planner} {tab==="calendar"&&<StudyCalendar onOpen={d=>{setDate(d);setTab("today");}}/>} {tab==="review"&&<ReviewQueue onRefresh={onRefresh}/>} {tab==="quiz"&&<QuizAndAssistant/>} {tab==="library"&&<ResourceLibrary/>} {tab==="progress"&&<Progress settings={settings}/>} 
  </>;
}

function TodayStudy({date,setDate,onRefresh}:{date:string;setDate:(v:string)=>void;onRefresh:()=>void}){
  const subjects=subjectsFor(date);const [focus,setFocus]=useState<{subject:string;task:string;minutes:number}|null>(null);
  const toggle=(subject:StudySubject,index:number)=>{const plan=readStore<any>(`pos_plan_${date}`,{});plan.studyList=(plan.studyList||[]).map((item:StudySubject)=>item.id===subject.id?{...item,plan:(item.plan||[]).map((task,i)=>i===index?{...task,done:!task.done,completedAt:!task.done?new Date().toISOString():undefined}:task)}:item);writeStore(`pos_plan_${date}`,plan);onRefresh();};
  return <><div className="between" style={{marginBottom:14,flexWrap:"wrap",gap:8}}><div><strong>Today&apos;s study</strong><div className="muted" style={{fontSize:12}}>Choose one task and start a distraction-free session.</div></div><input className="in" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>{subjects.length?subjects.map(subject=><div className="card" key={subject.id} style={{marginBottom:12}}><div className="between"><div><strong>{subject.label}</strong><div className="muted" style={{fontSize:12}}>{subject.brief||`${(subject.plan||[]).length} planned tasks`}</div></div><span className="in" style={{padding:"5px 9px"}}>{(subject.plan||[]).filter(x=>x.done).length}/{(subject.plan||[]).length}</span></div>{(subject.plan||[]).map((task,index)=><div className="row" key={index} style={{marginTop:10,paddingTop:10,borderTop:"1px solid var(--stroke)"}}><button className="btn ghost sm" onClick={()=>toggle(subject,index)}>{task.done?"✅":"⬜"}</button><div style={{flex:1,textDecoration:task.done?"line-through":"none"}}><b style={{fontSize:13}}>{task.task}</b><div className="muted" style={{fontSize:11}}>{task.time||"Focused block"}</div></div><button className="btn sm" disabled={task.done} onClick={()=>setFocus({subject:subject.label,task:task.task,minutes:mins(task.time)})}>▶ Start</button></div>)}</div>):<div className="card muted">No study scheduled for this date. Open Study Plan to add a subject.</div>}{focus&&<FocusTimer {...focus} onClose={()=>setFocus(null)} onSaved={onRefresh}/>}</>;
}

function FocusTimer({subject,task,minutes,onClose,onSaved}:{subject:string;task:string;minutes:number;onClose:()=>void;onSaved:()=>void}){const [seconds,setSeconds]=useState(minutes*60);const [running,setRunning]=useState(true);const [note,setNote]=useState("");const [distractions,setDistractions]=useState(0);useEffect(()=>{if(!running||seconds<=0)return;const id=setInterval(()=>setSeconds(x=>Math.max(0,x-1)),1000);return()=>clearInterval(id);},[running,seconds]);const save=()=>{const elapsed=Math.max(1,Math.round((minutes*60-seconds)/60));const all=studySessions();all.unshift({id:crypto.randomUUID(),date:localDate(),subject,minutes:elapsed,note,completedAt:new Date().toISOString()});writeStore("pos_study_sessions",all);onSaved();onClose();};return <div style={{position:"fixed",inset:0,zIndex:200,background:"rgba(3,7,18,.96)",display:"grid",placeItems:"center",padding:20}}><div className="card" style={{width:"min(620px,100%)",textAlign:"center"}}><div className="between"><span className="muted">FOCUS SESSION</span><button className="btn ghost sm" onClick={onClose}>✕</button></div><h2>{subject}</h2><p className="muted">{task}</p><div style={{fontSize:72,fontWeight:800,fontVariantNumeric:"tabular-nums",margin:"28px 0"}}>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div><div className="row" style={{justifyContent:"center",flexWrap:"wrap"}}><button className="btn" onClick={()=>setRunning(x=>!x)}>{running?"⏸ Pause":"▶ Resume"}</button><button className="btn ghost" onClick={()=>setSeconds(5*60)}>☕ 5m break</button><button className="btn ghost" onClick={()=>setDistractions(x=>x+1)}>Distraction +1 ({distractions})</button></div><textarea className="in" value={note} onChange={e=>setNote(e.target.value)} placeholder="Session note or what to do next…" style={{width:"100%",minHeight:90,marginTop:20}}/><button className="btn" onClick={save} style={{marginTop:12}}>💾 Finish and log session</button></div></div>;}

function CourseOverview(){const rows=collectSubjects(180,260);const grouped=new Map<string,{total:number;done:number;subject:StudySubject}>();rows.forEach(({subject})=>{const key=subject.courseId||subject.label;const row=grouped.get(key)||{total:0,done:0,subject};row.total++;if((subject.plan||[]).length&&(subject.plan||[]).every(x=>x.done))row.done++;grouped.set(key,row);});return <div className="grid g3" style={{marginBottom:16}}>{[...grouped.values()].slice(0,9).map(row=><div className="card" key={row.subject.courseId||row.subject.label}><strong>{row.subject.label.replace(/Day \d+:.*/,"")}</strong><div style={{fontSize:26,fontWeight:800,marginTop:10}}>{row.total?Math.round(row.done/row.total*100):0}%</div><div className="muted" style={{fontSize:12}}>{row.done}/{row.total} study days completed</div></div>)}</div>;}

function StudyCalendar({onOpen}:{onOpen:(date:string)=>void}){const days=Array.from({length:35},(_,i)=>addDays(localDate(),i-7));return <div className="card"><strong>Five-week study calendar</strong><div className="cal-grid" style={{marginTop:12}}>{days.map(date=>{const subjects=subjectsFor(date);const tasks=subjects.flatMap(x=>x.plan||[]);const done=tasks.filter(x=>x.done).length;return <button key={date} className="cal-cell" onClick={()=>onOpen(date)} title={`${date}: ${subjects.map(x=>x.label).join(", ")||"No study"}`} style={{border:date===localDate()?"1px solid #60a5fa":undefined,background:subjects.length?"rgba(168,85,247,.12)":undefined,cursor:"pointer"}}><div className="cd">{+date.slice(-2)}</div><div className="cs">{subjects.length?`${done}/${tasks.length}`:"—"}</div></button>;})}</div></div>;}

function ReviewQueue({onRefresh}:{onRefresh:()=>void}){const [items,setItems]=useState<ReviewItem[]>(()=>buildReviews());const today=localDate();const due=items.filter(x=>!x.done&&x.due<=today).sort((a,b)=>a.due.localeCompare(b.due));const done=(id:string)=>{const next=items.map(x=>x.id===id?{...x,done:true}:x);setItems(next);writeStore("pos_study_reviews",next);onRefresh();};return <div className="card"><div className="between"><div><strong>Spaced repetition queue</strong><div className="muted" style={{fontSize:12}}>Reviews are scheduled after 1, 3, 7, and 21 days.</div></div><span className="in" style={{padding:"5px 9px"}}>{due.length} due</span></div>{due.length?due.map(item=><div className="li" key={item.id}><span>🧠</span><div style={{flex:1}}><b>{item.subject}</b><div className="muted" style={{fontSize:12}}>{item.topic} · {item.interval}-day review</div></div><button className="btn sm" onClick={()=>done(item.id)}>Reviewed</button></div>):<div className="muted" style={{marginTop:16}}>You are caught up. Complete study tasks to generate future reviews.</div>}</div>;}

function QuizAndAssistant(){const all=collectSubjects(90,30).map(x=>x.subject);const unique=[...new Map(all.map(x=>[x.id||x.label,x])).values()];const [selected,setSelected]=useState(unique[0]?.id||"");const subject=unique.find(x=>x.id===selected)||unique[0];const [quiz,setQuiz]=useState<any[]>([]);const [answers,setAnswers]=useState<Record<number,string>>({});const [busy,setBusy]=useState(false);const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const context=subject?[subject.label,subject.brief,subject.notes,(subject.plan||[]).map(x=>x.task).join("; ")].filter(Boolean).join("\n").slice(0,12000):"";const generate=async()=>{setBusy(true);try{const r=await fetch("/api/study-quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:subject?.label||"Study",context})});const d=await r.json();setQuiz(d.questions||[]);}finally{setBusy(false);}};const ask=async()=>{setBusy(true);try{const r=await fetch("/api/study-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:subject?.label||"Study",context,question})});const d=await r.json();setAnswer(d.answer||d.error||"No answer available.");}finally{setBusy(false);}};return <><div className="card"><div className="between"><strong>Course-grounded quiz</strong><select className="in" value={selected} onChange={e=>setSelected(e.target.value)}>{unique.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></div><button className="btn" style={{marginTop:12}} onClick={generate} disabled={busy||!subject}>{busy?"Generating…":"Generate 5 questions"}</button>{quiz.map((q,i)=><div key={i} style={{marginTop:14,paddingTop:12,borderTop:"1px solid var(--stroke)"}}><b>{i+1}. {q.question}</b>{(q.options||[]).map((option:string)=><label className="row" key={option} style={{marginTop:7}}><input type="radio" name={`q${i}`} value={option} onChange={()=>setAnswers(x=>({...x,[i]:option}))}/><span>{option}</span></label>)}{answers[i]&&<div style={{fontSize:12,marginTop:7,color:answers[i]===q.answer?"#6ee7b7":"#fca5a5"}}>{answers[i]===q.answer?"Correct":"Answer: "+q.answer} · {q.explanation}</div>}</div>)}</div><div className="card" style={{marginTop:16}}><strong>Ask your course material</strong><div className="muted" style={{fontSize:12,marginTop:4}}>The selected subject&apos;s notes, plan, and description are sent as grounding context.</div><div className="row" style={{marginTop:12}}><input className="in" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about this topic…" style={{flex:1}}/><button className="btn" onClick={ask} disabled={busy||!question.trim()}>Ask</button></div>{answer&&<div style={{whiteSpace:"pre-wrap",lineHeight:1.65,marginTop:14}}>{answer}</div>}</div></>;}

function ResourceLibrary(){const [query,setQuery]=useState("");const rows=useMemo(()=>collectSubjects(180,260),[]);const filtered=rows.filter(({subject})=>JSON.stringify(subject).toLowerCase().includes(query.toLowerCase())).slice(0,80);return <><div className="card"><strong>Search all study content</strong><input className="in" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search courses, notes, PDFs, tasks, code…" style={{width:"100%",marginTop:10}}/></div><div className="grid g2" style={{marginTop:14}}>{filtered.map(({date,subject})=><div className="card" key={`${date}-${subject.id}`}><div className="between"><strong>{subject.label}</strong><span className="muted" style={{fontSize:11}}>{date}</span></div><div className="muted" style={{fontSize:12,marginTop:6}}>{subject.brief||`${(subject.plan||[]).length} tasks`}</div><div className="row" style={{marginTop:10,flexWrap:"wrap"}}>{subject.pdf&&<a className="btn ghost sm" href={subject.pdf} target="_blank">PDF</a>}{subject.resource&&<a className="btn ghost sm" href={subject.resource.match(/https?:\/\/\S+/)?.[0]||subject.resource} target="_blank">Resource</a>}{subject.courseVideo&&<a className="btn ghost sm" href={subject.courseVideo} target="_blank">Video</a>}{subject.notes&&<span className="in" style={{padding:"5px 8px"}}>Notes ✓</span>}{subject.codeFile&&<span className="in" style={{padding:"5px 8px"}}>Code ✓</span>}</div></div>)}</div></>;}

function Progress({settings}:{settings:AppSettings}){void settings;const sessions=studySessions();const week=Array.from({length:7},(_,i)=>addDays(localDate(),i-6));const rows=week.map(date=>({date,minutes:sessions.filter(x=>x.date===date).reduce((a,x)=>a+x.minutes,0),planned:subjectsFor(date).flatMap(x=>x.plan||[]).length,done:subjectsFor(date).flatMap(x=>x.plan||[]).filter(x=>x.done).length}));const total=rows.reduce((a,x)=>a+x.minutes,0);const completion=rows.reduce((a,x)=>a+x.done,0),planned=rows.reduce((a,x)=>a+x.planned,0);const weak=collectSubjects(45,0).map(x=>x.subject).filter(x=>(x.plan||[]).some(t=>!t.done)).slice(0,5);return <><div className="grid g3"><div className="card"><div className="lbl">FOCUS TIME</div><div className="val">{Math.floor(total/60)}h {total%60}m</div><div className="muted">last 7 days</div></div><div className="card"><div className="lbl">PLAN COMPLETION</div><div className="val">{planned?Math.round(completion/planned*100):0}%</div><div className="muted">{completion}/{planned} tasks</div></div><div className="card"><div className="lbl">SESSIONS</div><div className="val">{sessions.filter(x=>week.includes(x.date)).length}</div><div className="muted">logged this week</div></div></div><div className="grid g2" style={{marginTop:16}}><div className="card"><strong>Planned vs completed</strong>{rows.map(x=><div className="between" key={x.date} style={{marginTop:10}}><span>{new Date(`${x.date}T12:00`).toLocaleDateString(undefined,{weekday:"short"})}</span><span className="muted">{x.done}/{x.planned} tasks · {x.minutes} min</span></div>)}</div><div className="card"><strong>Revision backlog</strong>{weak.length?weak.map(x=><div className="li" key={x.id}><span>○</span><span>{x.label}</span></div>):<div className="muted" style={{marginTop:12}}>No unfinished topics in the recent window.</div>}</div></div></>;}
