"use client";
import { useMemo,useState,type ReactNode } from "react";
import { readJson } from "@/lib/client-storage";
type Tab="daily"|"mistakes"|"vocabulary"|"scenarios"|"progress";
const ds=(d=new Date())=>d.toISOString().slice(0,10);
export default function EnglishWorkspace({practice}:{practice:ReactNode}){const [tab,setTab]=useState<Tab>("daily");const tabs:[Tab,string][]=[["daily","Daily session"],["mistakes","Mistake notebook"],["vocabulary","Vocabulary"],["scenarios","Scenarios"],["progress","Progress"]];return <><div className="head"><h1>English Fluency</h1><p>Speak, write, review mistakes, and build natural vocabulary.</p></div><div className="row" style={{gap:8,flexWrap:"wrap",marginBottom:16}}>{tabs.map(([k,l])=><button className={`btn ${tab===k?"":"ghost"} sm`} key={k} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==="daily"&&<><DailyGuide/>{practice}</>}{tab==="mistakes"&&<Mistakes/>}{tab==="vocabulary"&&<Vocabulary/>}{tab==="scenarios"&&<Scenarios/>}{tab==="progress"&&<EnglishProgress/>}</>}
function DailyGuide(){return <div className="grid g5" style={{marginBottom:16}}>{[["Vocabulary","5 min"],["Lesson","10 min"],["Speaking","10 min"],["Pronunciation","5 min"],["Writing","10 min"]].map(([x,t],i)=><div className="card" key={x}><div className="lbl">STEP {i+1}</div><strong>{x}</strong><div className="muted">{t}</div></div>)}</div>}
function recentEnglish(){const out:any[]=[];for(let i=0;i<90;i++){const d=new Date();d.setDate(d.getDate()-i);const date=ds(d);const data=readJson<any>(`pos_eng_${date}`,null);if(data)out.push({date,data});}return out;}
function Mistakes(){const rows=useMemo(()=>recentEnglish().flatMap(({date,data})=>(data.chat||[]).flatMap((m:any)=>(m.issues||[]).map((issue:string)=>({date,issue,better:m.corrected||""})))),[]);const [notes,setNotes]=useState<any[]>(()=>readJson("pos_eng_mistakes",[]));const all=[...notes,...rows];const add=()=>{const next=[{date:ds(),issue:"New mistake",better:"Correct form"},...notes];setNotes(next);localStorage.setItem("pos_eng_mistakes",JSON.stringify(next));};return <div className="card"><div className="between"><div><strong>Mistake notebook</strong><div className="muted">Corrections collected from speaking sessions.</div></div><button className="btn sm" onClick={add}>Add manually</button></div>{all.length?all.slice(0,100).map((x,i)=><div className="li" key={`${x.date}-${i}`}><span>✏️</span><div><div>{x.issue}</div>{x.better&&<div className="muted" style={{fontSize:12}}>Better: {x.better}</div>}</div><span className="muted" style={{marginLeft:"auto",fontSize:11}}>{x.date}</span></div>):<div className="muted" style={{marginTop:16}}>Complete a speaking session to collect corrections.</div>}</div>}
function Vocabulary(){const [items,setItems]=useState<any[]>(()=>readJson("pos_eng_vocab",[]));const [word,setWord]=useState("");const save=(x:any[])=>{setItems(x);localStorage.setItem("pos_eng_vocab",JSON.stringify(x));};const add=()=>{if(!word.trim())return;save([{id:crypto.randomUUID(),word,meaning:"",example:"",level:0,due:ds()},...items]);setWord("");};const review=(id:string)=>save(items.map(x=>x.id===id?{...x,level:Math.min(4,(x.level||0)+1),due:new Date(Date.now()+[1,3,7,21,45][Math.min(4,(x.level||0)+1)]*86400000).toISOString().slice(0,10)}:x));return <div className="card"><div className="between"><strong>Spaced vocabulary review</strong><div className="row"><input className="in" value={word} onChange={e=>setWord(e.target.value)} placeholder="word or phrase"/><button className="btn sm" onClick={add}>Add</button></div></div>{items.map((x,i)=><div className="card" key={x.id} style={{marginTop:10,background:"rgba(255,255,255,.03)"}}><div className="between"><input className="in" value={x.word} onChange={e=>save(items.map((v,j)=>j===i?{...v,word:e.target.value}:v))}/><span className="muted">Due {x.due}</span></div><input className="in" value={x.meaning} onChange={e=>save(items.map((v,j)=>j===i?{...v,meaning:e.target.value}:v))} placeholder="Meaning" style={{width:"100%",marginTop:7}}/><input className="in" value={x.example} onChange={e=>save(items.map((v,j)=>j===i?{...v,example:e.target.value}:v))} placeholder="Natural example" style={{width:"100%",marginTop:7}}/><button className="btn sm" onClick={()=>review(x.id)} style={{marginTop:7}}>Reviewed</button></div>)}</div>}
function Scenarios(){const scenarios=["Job interview","Business meeting","Presentation Q&A","Networking","Negotiation","Customer support","Travel & airport","Casual conversation"];return <div className="grid g2">{scenarios.map(x=><div className="card" key={x}><strong>{x}</strong><p className="muted">Open Daily session, select this scenario in Speaking Coach, then complete a 10-minute conversation and request feedback.</p><div className="in" style={{display:"inline-block",padding:"5px 9px"}}>Speaking · corrections · report</div></div>)}</div>}
function EnglishProgress(){const rows=recentEnglish();let messages=0,essays=0,reports=0;rows.forEach(({data})=>{messages+=(data.chat||[]).filter((x:any)=>x.role==="user").length;if(data.essayResult)essays++;if(data.report)reports++;});const vocab=readJson<any[]>("pos_eng_vocab",[]),mistakes=rows.flatMap(({data})=>(data.chat||[]).flatMap((x:any)=>x.issues||[])).length;return <><div className="grid g4"><div className="card"><div className="lbl">SPEAKING TURNS</div><div className="val">{messages}</div></div><div className="card"><div className="lbl">WRITING REVIEWS</div><div className="val">{essays}</div></div><div className="card"><div className="lbl">SESSION REPORTS</div><div className="val">{reports}</div></div><div className="card"><div className="lbl">VOCABULARY</div><div className="val">{vocab.length}</div></div></div><div className="card" style={{marginTop:16}}><strong>Current focus</strong><p>{mistakes?`${mistakes} correction points were captured. Review the Mistake notebook and practise the repeated patterns.`:"Complete a speaking session to establish your grammar and fluency baseline."}</p><div className="muted">Pronunciation feedback is inferred from browser speech-to-text, not raw phoneme analysis.</div></div></>}
